swagger: "2.0"
info:
  title: Go Swagger demo
  version: 0.1.0
consumes:
- application/json
produces:
- application/json
schemes:
- http

paths:
  /status:
    get:
      operationId: getStatus
      tags:
        - status
      responses:
        200:
          description: service ok
          schema:
            $ref: '#/definitions/status'
  /employee:
    get:
      operationId: listEmployees
      tags:
        - employee
      responses:
        200:
          description: all employees
          schema:
            type: array
            items:
              $ref: '#/definitions/employee'
  /employee/{employeeId}:
    get:
      operationId: getEmployee
      tags:
        - employee
      parameters:
        - name: employeeId
          in: path
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: find employee by id
          schema:
            $ref: '#/definitions/employee'
        404:
          description: employee not found
          schema:
            $ref: '#/definitions/error'
definitions:
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
        description: re-represents the http status code of the request
      message:
        type: string
        description: a human readable description of the problem
  status:
    type: object
    properties:
      ok:
        type: string
        enum: [ok, fail]
      services:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            ok:
              type: string
              enum: [ok, fail]
  employee:
    type: object
    required:
      - first_name
      - last_name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      first_name:
        type: string
      last_name:
        type: string
