version: "3"
services:
  overview:
    image: cosmtrek/air:v1.10
    restart: always
    working_dir: /go/src/benrowe/demo-web-services/
    volumes:
      - go_src:/go/src:cached
      - ./:/go/src/benrowe/demo-web-services/:cached
    ports:
      - 800:80
  go-gqlgen:
    build:
      context: ./src/go-gqlgen/docker
    restart: always
    working_dir: /go/src/benrowe/demo-web-services/src/go-gqlgen
    volumes:
      - go_src:/go/src:cached
      - go_pkg:/go/pkg:cached
      - ./src:/go/src/benrowe/demo-web-services/src/
    ports:
      - 801:8888
    depends_on:
      - database
      - overview
      - oauth
    environment:
      - DB_HOST=database
      - DB_DATABASE=employees
  go-grpc:
    image: cosmtrek/air:v1.10
    restart: always
    working_dir: /go/src/benrowe/demo-web-services/src/go-grpc
    volumes:
      - go_src:/go/src:cached
      - go_pkg:/go/pkg:cached
      - ./src:/go/src/benrowe/demo-web-services/src/:cached
    ports:
      - 802:80
    depends_on:
      - database
      - overview
      - oauth
  go-swagger:
    image: cosmtrek/air:v1.10
    restart: always
    working_dir: /go/src/benrowe/demo-web-services/src/go-swagger
    volumes:
      - go_src:/go/src:cached
      - go_pkg:/go/pkg:cached
      - ./src:/go/src/benrowe/demo-web-services/src/:cached
    ports:
      - 803:80
    depends_on:
      - database
      - overview
      - oauth
  database:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  oauth-migrate:
    image: oryd/hydra:latest
    environment:
      - DSN=mysql://root:password@tcp(database:3306)/mysql?max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure
  oauth:
    image: oryd/hydra:latest
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:3000/consent
      - URLS_LOGIN=http://127.0.0.1:3000/login
      - URLS_LOGOUT=http://127.0.0.1:3000/logout
      - DSN=mysql://root:password@tcp(database:3306)/oauth?max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_TYPES_SUPPORTED=public,pairwise
      - OIDC_SUBJECT_TYPE_PAIRWISE_SALT=youReallyNeedToChangeThis
    restart: unless-stopped
    depends_on:
      - oauth-migrate
  consent:
    image: oryd/hydra-login-consent-node:v1.0.0-rc.10
    environment:
      - HYDRA_ADMIN_URL=http://oauth:4445
    ports:
      - "3000:3000"
    restart: unless-stopped
volumes:
  go_src:
  go_pkg:

