version: "3"
services:
  overview:
    image: cosmtrek/air
    restart: always
    working_dir: /go/src/benrowe/demo-web-services/
    volumes:
      - go_src:/go/src:cached
      - ./:/go/src/benrowe/demo-web-services/:cached
    ports:
      - 800:80
  go-gqlgen:
    build:
      context: ./src/go-gqlgen/docker
    restart: always
    working_dir: /go/src/benrowe/demo-web-services/src/go-gqlgen
    volumes:
      - go_src:/go/src:cached
      - go_pkg:/go/pkg:cached
      - ./src:/go/src/benrowe/demo-web-services/src/:cached
    ports:
      - 801:80
    depends_on:
      - database
      - overview
    environment:
      - DB_HOST=database
      - DB_DATABASE=employees
  go-grpc:
    image: cosmtrek/air
    restart: always
    working_dir: /go/src/benrowe/demo-web-services/src/go-grpc
    volumes:
      - go_src:/go/src:cached
      - go_pkg:/go/pkg:cached
      - ./src:/go/src/benrowe/demo-web-services/src/:cached
    ports:
      - 802:80
    depends_on:
      - database
      - overview
  go-swagger:
    image: cosmtrek/air
    restart: always
    working_dir: /go/src/benrowe/demo-web-services/src/go-swagger
    volumes:
      - go_src:/go/src:cached
      - go_pkg:/go/pkg:cached
      - ./src:/go/src/benrowe/demo-web-services/src/:cached
    ports:
      - 803:80
    depends_on:
      - database
      - overview
  database:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sample
    volumes:
      - ./sampledb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  go_src:
  go_pkg:

