name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Fetch Tools
        run: |
          go get -u golang.org/x/lint/golint

      - name: Syntax check
        run: |
          test -z "$(gofmt -l ./src/)"
          test -z "$(golint ./...)"

      - name: Build
        run: |
          go build -v ./src/go-gqlgen/main.go
          go build -v ./src/go-grpc/main.go
          go build -v ./src/go-swagger/main.go

      - name: Test
        run: |
          go test ./src/
