name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Fetch Tools
        run: |
          go get -u golang.org/x/lint/golint

      - name: Get dependencies
        working-directory: ./src
        run: |
          go get -v -t -d ./...

      - name: Syntax check
        working-directory: ./src
        run: |
          test -z "$(gofmt -l ./)"
          test -z "$(golint ./...)"

      - name: Build
        working-directory: ./src
        run: |
          go build -v ./go-gqlgen/main.go
          go build -v ./go-grpc/main.go
          go build -v ./go-swagger/main.go

      - name: Test
        working-directory: ./src
        run: |
          go test ./...
