name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Fetch Tools
        run: |
          go get -u golang.org/x/lint/golint

      - name: Get dependencies
        run: |
          (cd src ; go get -v -t -d ./...)

      - name: Syntax check
        run: |
          test -z "$(gofmt -l ./src/)"
          test -z "$(golint ./src/...)"

      - name: Build
        run: |
          (cd src ; go build -v ./go-gqlgen/main.go)
          (cd src ; go build -v ./go-grpc/main.go)
          (cd src ; go build -v ./go-swagger/main.go)

      - name: Test
        run: |
          go test ./src/
